locale: "en"
title: Academic Programmer
email: me@academic-programmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /posts/:year/:month/:title/




twitter_username: svamann
github_username:  salsolatragus

markdown: kramdown
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
paginate_path: /page:num/
