locale: "en"
title: Academics code
title_separator: "::"
name: "Sven Amann"
email: sven@academicscode.com
description: >
  Software, the final frontier.
  These are the voyages of a programmer. His five-year mission: to explore the
  strange world of Academia, to seek his PhD while staying true to Clean Code,
  to boldly go where no man has gone before.
url: "http://academicscode.com"
baseurl: ""
theme: minimal-mistakes-jekyll
permalink: /posts/:year/:month/:title/

google_site_verification: 0VPP-0JoECBukusgQCRSnujIckDxTfkl2nHFrN14jtQ

analytics:
  provider: "google"
  google:
    tracking_id: UA-62752140-4

teaser: "/assets/images/teaser_coding_academics_500x300.png"

twitter:
  username: svamann
social:
  links:
    - "https://twitter.com/svamann"
    - "https://de.linkedin.com/in/sven-amann-b4a14979"
    - "https://www.xing.com/profile/Sven_Amann5"

category_archive:
  type: jekyll-archives
  path: /posts/categories/

jekyll-archives:
  enabled:
    - categories
  layout: archive-taxonomy
  permalinks:
    category: /posts/categories/:name/

paginate: 5
paginate_path: /page:num/

author:
  name: "Sven Amann"
  avatar: "/assets/images/avatar-sven.png"
  bio: "Just a programmer in Academia"
  uri: http://sven-amann.de
  twitter: svamann
  linkedin: sven-amann-b4a14979
  #xing: Sven_Amann5
  github: salsolatragus
  #bitbucket: salsolatragus
  stackoverflow: 1372671/sven-amann
  youtube: letsdeveloper

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true

markdown: kramdown

comments:
  provider: "disqus"
  disqus:
    shortname: "academicscode-com"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
